
from db.connection import execute_query


def alter_table():
    execute_query('ALTER TABLE questions ALTER COLUMN "user_id" TYPE TEXT')
    execute_query('ALTER TABLE "ORDERS" ALTER COLUMN "USERID" TYPE TEXT')
    execute_query('ALTER TABLE "Users" ALTER COLUMN "USERTELEGRAMID" TYPE TEXT')
    execute_query('ALTER TABLE "ORDERS" ALTER COLUMN "PRICE" TYPE TEXT')

def create_table():
    execute_query('CREATE TABLE IF NOT EXISTS questions (id SERIAL PRIMARY KEY, user_id TEXT, message TEXT)')
    execute_query('CREATE TABLE IF NOT EXISTS "ORDERS" ("USERID" TEXT NOT NULL UNIQUE, "DESCRIPTION" TEXT NOT NULL, "ORDERID" SERIAL PRIMARY KEY, "STATUS" TEXT NOT NULL, "PRICE" INTEGER);')
    execute_query('CREATE TABLE IF NOT EXISTS "Users" ("USERNAME" TEXT NOT NULL, "USERTELEGRAMID" TEXT NOT NULL UNIQUE, "USERID" SERIAL UNIQUE, "BOTDILLER" INTEGER NOT NULL DEFAULT 0, "BANNED" INTEGER NOT NULL DEFAULT 0, "ORDERS" INTEGER DEFAULT 1, "EDITS" INTEGER DEFAULT 2);')